name: rukkit
main: com.supermomonga.Rukkit.JRubyPlugin
version: 1.0.0
website: http://blog.supermomonga.com/
author: supermomonga
description: benri
commands:
  rukkit:
    description: rukkit commands
    usage: /rukkit [anything]
aliases:
  rkt:
    - "rukkit $1-"
rukkit:
  plugin_dir:
    "file://./user_plugins/"
  plugins:

