name: rukkit
main: com.supermomonga.rukkit.JRubyPlugin
version: 1.0.1
website: http://rukkit.com/
author: supermomonga
description: benri
commands:
  rukkit:
    description: rukkit commands
    usage: /rukkit [anything]
    aliases:
      - rkt

